import pkg from "../../package.json";

export const LANG_MAP = {
    "": "js",
    ".mjs": "js",
    ".jsx": "jsx",
    ".ts": "ts",
    ".tsx": "tsx",
    ".php": "php",
    ".json": "json",
    ".d.ts": "ts",
};

export const TEXT_HEADERS = {
    toc: "##==== Combined Scope ====",
    path: (p) => `##==== path: ${p} ====`,
    regionStart: (p) => `##region ${p}`,
    regionEnd: "##endregion",
};

export const MD_FOOTER = ["\n---", "*Generated with [Prodex](https://github.com/emxhive/prodex) — Codebase decoded.*", `<!-- PRODEx v${pkg.version} | ${new Date().toISOString()} -->`].join("\n");
export const MD_HEADER = "*Generated by [Prodex](https://github.com/emxhive/prodex#readme)*";
export const INDEX_RANGE_PLACEHOLDER = "L?-L?";
export const LLM_NOTE = "> Note for LLMs: `Lx-Ly` ranges refer to lines in this Prodex trace file, not the original source files. Index metadata is provided via the HTML comment markers in this section.";